### ISSUE TITLE
Support flash "now" parameter, for saving information for current requests

### ISSUE THREAD

**Issue by s3ththompson** [mzur/kirby-flash#2]
`kirby-flash` works really well when I want to save a success message or an error for the next page load, and I return a redirect from a controller.

However, I'd like to use `kirby-flash` in situations where I render a 422 response immediately after a form error. In this case, I'd like the flash error message to show up in the response for the current request (and not the subsequent page load).

[Rails has a similar pattern](https://spartchou.gitbooks.io/ruby-on-rails-basic/content/syntax/flash_vs_flashnow.html), and the flash object has a [`now` method](https://api.rubyonrails.org/v6.1.0/classes/ActionDispatch/Flash/FlashHash.html#method-i-now) to support this use case.

Would you be open to this feature?

I think the cleanest API would probably be to support a 3rd, optional boolean argument called "now" on `flash->set()` and the `flash` helper. Under the hood, this would store the data in a separate temporary array on the `Flash` instance, which would not be persisted to the session. `flash` and `flash->get()` would read from both the session data and the temporary data when looking for a key.

**Comment by mzur** [comment]
Discussed in #3.
